apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sdp-prod-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: sdp-prod-backend-secrets
    creationPolicy: Owner
  data:
    # Database URL
    - secretKey: DATABASE_URL
      remoteRef:
        key: sdp/prod/db/url
        property: DATABASE_URL
    
    # SEP-10 keys
    - secretKey: SEP10_SIGNING_PUBLIC_KEY
      remoteRef:
        key: sdp/prod/sep10/public
    
    - secretKey: SEP10_SIGNING_PRIVATE_KEY
      remoteRef:
        key: sdp/prod/sep10/private
    
    # SEP-24 JWT Secret
    - secretKey: SEP24_JWT_SECRET
      remoteRef:
        key: sdp/prod/sep24/jwtSecret
    
    # EC256 Private Key
    - secretKey: EC256_PRIVATE_KEY
      remoteRef:
        key: sdp/prod/ec256/private
    
    # Admin Account
    - secretKey: ADMIN_ACCOUNT
      remoteRef:
        key: sdp/prod/admin/account
    
    # Admin API Key
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: sdp/prod/admin/apiKey
    
    # Distribution Seed
    - secretKey: DISTRIBUTION_SEED
      remoteRef:
        key: sdp/prod/distribution/seed
    
    # Distribution Account Encryption Passphrase
    - secretKey: DISTRIBUTION_ACCOUNT_ENCRYPTION_PASSPHRASE
      remoteRef:
        key: sdp/prod/distribution/encryptionPassphrase
    
    # Channel Account Encryption Passphrase
    - secretKey: CHANNEL_ACCOUNT_ENCRYPTION_PASSPHRASE
      remoteRef:
        key: sdp/prod/channel/encryptionPassphrase

