apiVersion: v1
kind: ServiceAccount
metadata:
  name: sdp-core
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::084034390838:role/sdp-core-irsa
  labels:
    app.kubernetes.io/name: stellar-disbursement-platform
    app.kubernetes.io/component: sdp-core

